### ISSUE TITLE
Abortable requests

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/tg-resources#34]
I think adding support for `Aborting requests` requires some more planning due to the differences between `fetch` and `superagent` in how they deal with aborting requests.

In fetch one needs to provide an [AbortController.signal](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) in the arguments to the `fetch` call. The controller itself has a method `abort` which can be called to cancel the request. When a request is cancelled it's promise is rejected. 

However, with superagent - `abort` is a method on the request. Upon abort ~~the promises behaves similarly to fetch.~~ It actually doesn't, we need to add a listener to `abort` event and reject via that.

Based on this, I have a couple of questions that need to get answered before we agree upon the final API for abortable requests.

1. Should we mimic fetch style api or go with something else entirely?
2. Can we have the same api regardless of the backend (fetch vs superagent)?
3. Can we still keep our Resource stateless?
4. How would this affect `saga-resource`?

# Progress

- [x] Agree on an Api
- [x] Implementation for fetch
- [x] Implementation for superagent
- [x] Test in react-native
- [x] Documentation update
- [x] Saga-resource integration

**Comment by Jyrno42** [comment]
for reference rgs. react-native: https://github.com/facebook/react-native/issues/18115

**Comment by Jyrno42** [comment]
Got it working with `fetch` backend. Will try to get `superagent` to work with the same tg-resources API soon. Note, I also need to test this on react-native to know whether we need the workaround or not.

Had to swap out `isomorphic-fetch` with `cross-fetch` since we needed an updated version of `node-fetch` however `isomorphic-fetch` seems to be abandoned.

**Comment by Jyrno42** [comment]
Superagent now also works

**Comment by Jyrno42** [comment]
Sad news about react-native, currently I did not manage to get aborting to work. See my testing repo here: https://github.com/Jyrno42/rn-tg-resources-tester. The following commit contains a testcase for aborting a request on react native and some explanations on what I tried to get aborting to work 

https://github.com/Jyrno42/rn-tg-resources-tester/commit/58f81ed36a91a81bd29d47f4687d77e22a84cd05

**Comment by Jyrno42** [comment]
We should do a release without RN support. We should also try to advocate (or do it ourselves) the AbortController thing inside rn core.

**Comment by metsavaht** [comment]
Released in [v3.1.0](https://github.com/thorgate/tg-resources/releases/tag/v3.1.0)

**Comment by Jyrno42** [comment]
Some progress on react-native support - got it working with `abortcontroller-polyfill` (see https://github.com/thorgate/tg-resources/pull/48). Once that is merged I would like to do a new release.

After that I would focus my efforts towards getting https://github.com/facebook/react-native/issues/18115 resolved. Seem to get it working by updating whatwg-fetch inside react-native core manually and using `import 'abortcontroller-polyfill/dist/abortcontroller-polyfill-only'` but I have to do a bit more testing with that. I also need to put back the changes to whatwg-fetch that are done in react-native master before I can submit a PR about it.
