### ISSUE TITLE
createRouter: Allow passing configuration to created resources

### ISSUE THREAD

**Issue by Jyrno42** [thorgate/tg-resources#35]
Currently `createRouter` does not have a way to pass configuration parameters to created resources. This prevents some of the users to get full advantages of the type-checking since they have to rely on direct instantiation (which we might move away from in the future).

Some ideas on the syntax:

```
const api = createRouter({
    dogs: '/dogs', // no configuration
    dogsWithParams: [
        '/dogs',
        {
            statusValidationError: [400, 401, 403],
            // ... rest of config ...
        },
    ],
    dogsWithParamsAlt: {
        apiEndpoint: '/dogs',

        statusValidationError: [400, 401, 403],
        // ... rest of config ...
    },
}, {
    apiRoot: 'https://example.com',
});
```

**Comment by Jyrno42** [comment]
Also, I think nesting of `createRouter` calls should be supported as well:

```
const api = createRouter({
    dogs: '/dogs',

   alternative: createRouter({
       dogs: '/dogs',
   }, {
       apiRoot: 'https://server2.example.com',
   }),
}, {
    apiRoot: 'https://server1.example.com',
});
```

**Comment by metsavaht** [comment]
I think it should be possible to get support for all of these options, will test out all.
I'll deal with it over the weekend or next week.

**Comment by metsavaht** [comment]
As part of this, I would like to remove separate implementation of `createRouter` used in `redux-saga` integration package. I'm thinking of adding helper function to create resource that could be changed for `redux-saga` integration package so `createRouter` could be used like:
```
import { FetchResource } from '@tg-resources/fetch';
import { createSagaResource } from '@tg-resources/redux-saga-router';
import { createRouter } from 'tg-resources';

const api = createRouter({
    dogs: '/dogs',
}, {
    apiRoot: 'https://server1.example.com',
}, FetchResource, createSagaResource);
```

Adding extra parameter to `createRouter` which will be optional and will use default if not provided, `createResource` will have following signature:
```
// Default will return constructed Resouce instance
const createResource = (resourceKlass, apiEndpoint, config) => ResourceKlass
```
